### ISSUE TITLE
Copyright infringement.

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/proprietary_vendor_oneplus_sm8150-common#1]
https://github.com/crdroidandroid/proprietary_vendor_oneplus_sm8150-common/commit/d3177598df394c7dced6fa7d7df295273fb475c8

I have done the work for you.
https://forum.xda-developers.com/t/rom-android-12-op7t-pro-unofficial-crdroid-v8-1-20-january-2022.4390749/#post-86306895
https://forum.xda-developers.com/t/rom-android-12-op7t-pro-unofficial-crdroid-v8-1-20-january-2022.4390749/#post-86318647

I even warned you - https://forum.xda-developers.com/t/rom-android-12-op7t-pro-unofficial-crdroid-v8-1-20-january-2022.4390749/#post-86345211
Why is there another person as the author of the commit?

I will not deal with you henceforth.

You are ordinary thieves

**Comment by gwolf2u** [comment]
Lol really...
I didn't use your exact commits but I did give credit
https://github.com/crdroidandroid/android_device_oneplus_sm8150-common/commit/f6f040d9074cd6b7fa5a5dcff5499afd1d93bab6
Anyway, will correct author if that's what you want
https://github.com/crdroidandroid/proprietary_vendor_oneplus_sm8150-common/commit/a62b11dd3ab4b298345ca89ed0b8e6eee979bda5
Enjoy the drama 

Also can't expect to read a forum am not part of... just for info
Those that know me, will know am a good guy and you could have pm on telegram or so

**Comment by ShevT** [comment]
Did you somehow magically get byte-for-byte files matching my commits? Compare the libnfc-nci.conf, libnfc-nxp.conf files from my commits with yours and see that they are identical.

> Those that know me, will know am a good guy and you could have pm on telegram or so

If your gerrit would be open to everyone, then I would point it out. Or rather, I would post the fixes there myself.

Perhaps you are a good person. But those who gave you these corrections - no. Thank you, the conflict is over.
I would like to see Your gerrit. I'm not bad either.

**Comment by gwolf2u** [comment]
we don't have gerrit
also gwolf2u @ telegram for future

**Comment by ShevT** [comment]
> we don't have gerrit

it's a pity 

> also gwolf2u @ telegram for future

Ok. Tanks
